# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02ef23770428f912dcfe0afbfcca8b01e260e2ee87cf7e3c2a01b9457689a758f1e0d6dea1e3bd37a57747fd5792ff53468cc3e78835d07b394a80b8cb330f6e

test:
  secret_key_base: 9338e4d9b464149eccc3747ce45c5804691a2c29f733eb44d7a29b2aa852a32529ea1c2f2f9a6601e7875dfb7f269058b268047d709d9ae925e1ff916a341206

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
